config/routes.rb
Rails.application.routes.draw do

  get 'charges/create'

  devise_for :users

  get 'welcome/index'

  get 'welcome/about'

  root to: 'welcome#index'

  resources :users do
    member do
      post :downgrade
    end
  end

  resources :wikis

  resources :charges, only: [:new, :create]

  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki

  @user_options = User.all.map { |u| [ u.email, u.id] }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :wikis
  has_many :collaborators
  has_many :wikis, through: :collaborators

  before_save { self.email = email.downcase }
  after_initialize { self.role ||= :standard }

  enum role: [:standard, :admin, :premium]

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base

  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  scope :visible_to, -> (user) { user ? where(private: false) : 'There was an error.' }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to :back || root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation) }
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create
    @user = current_user

    #Creates a Stripe Customer object, for associating with the charge.
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )


  # Payment being made
  charge = Stripe::Charge.create(
    customer: customer.id,
    amount: 15_00,
    description: "Upgrade to Premium Membership - #{current_user.email}",
    currency: 'usd'
  )

  @user.update_attributes(role: 'premium')
  #@user.role = 'premium'
  #@user.save

  flash[:notice] = "Thanks for the payment, #{current_user.email}! You can now create and edit private wikis."
  redirect_to root_path

  # Stripe will send back CardErrors, with friendly messages when something goes wrong.
  # This `rescue block` catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Membership - #{current_user.name}",
      amount: 15_00
    }
  end

  private

  def upgrade_user_role
    @user.role = 'premium'
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki

  def new
    @collaborator = Collaborator.new
  end

  def create
    @collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: params[:user_id])


    if @collaborator.save
      flash[:notice] = "Collaborator was added to this wiki."
      redirect_to @wiki
    else
      flash[:error] = "Collaborator was not added. Please try again."
      render :show
    end
   end

  def destroy
    # @wiki.users.delete(user)
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator was removed from this wiki."
      redirect_to @wiki
    else
      flash[:error] = "Collaborator was not removed. Please try again."
      render :show
    end
  end

  private

  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    if current_user.present?
      @user = params[:id] ? User.find(params[:id]) : current_user
    else
      redirect_to root_path
    end
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def downgrade
    @user = User.find(params[:id])
    @user.role = 'standard'

    if @user.save
      flash[:notice] = "You've been downgraded to standard. Your private wikis are now public."
      redirect_to :back
    else
      flash[:error] = "There was an error creating your account. Please try again."
      redirect_to :back
    end

    @user_wikis = @user.wikis.where(private: true)

    @user_wikis.each do |makepub|
      makepub.update_attributes(private: false)
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_filter :authenticate_user!, except: [ :index, :about ]

  def index
  end

  def about
  end

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  include ApplicationHelper

  before_filter :authenticate_user!

  after_action :verify_authorized, :except => :index

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
    @user = current_user
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @user = current_user
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      redirect_to @wiki, notice: "Wiki was saved successfully."
    else
      flash[:error] = "Error creating wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
    @collaborator = Collaborator.new
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    @wiki.assign_attributes(wiki_params)
    @wiki.user_ids = params[:wiki][:user_ids] if params[:wiki][:user_ids].present?

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash[:error] = "Error saving wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash[:error] = "There was an error deleting the wiki."
      render :show
    end
  end

 private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :user, :user_ids)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end

  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4> Upgrade to Premium Membership </h4>
    <div>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
    </div>
<% end %>

<% content_for :analytic do %>
  <script type="text/javascript"> $(document).ready(function(){ blocmetrics.report("Payment Page Visit"); }); </script>
<% end %>

app/views/collaborators/_form.html.erb
<% if @wiki.user_id == current_user.id || current_user.admin? %>
		<div class="form-group">
			<% @users.each do |user| %>
				<h4><%= user.email %> </h4>

				<% if @wiki.users.include? user %>
					<div>
					<%= link_to "Remove Collaborator", wiki_collaborator_path(@wiki, @wiki.collaborators.find_by_user_id(user.id).id), method: :delete, class: 'btn btn-danger' %>
				  </div>
				<% else %>
					<div>
					<%= link_to "Add Collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: 'btn btn-info' %>
					</div>
				<% end %>
			<% end %>
		</div>

<% end %>

app/views/collaborators/_users.html.erb
<h4>Collaborators</h4>
<ul>
	<% @wiki.collaborators.each do |collaborator| %>
		<li>
			<h4><%= collaborator.user.email %> <%= link_to "", "/wikis/#{@wiki.id}/collaborators/#{collaborator.id}", method: :delete, class: 'glyphicon glyphicon-remove' %> </h4>
		</li>
	<% end %>
</ul>

app/views/collaborators/new.html.erb
<h1>Add Collaborator</h1>

<%= form_for [@wiki] do |f| %>

  <% if @wiki.errors.any? %>
     <div class="alert alert-danger">
       <h4>There are <%= pluralize(@wiki.errors.count, "error") %>.</h4>
       <ul>
         <% @wiki.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
  <% end %>

  <%= collection_check_boxes(:wiki, :user_ids, User.all - [f.object.user], :id, :email) do |u| %>
    <div class="checkbox">
      <%= u.label do %>
        <%= u.check_box %>
        <%= u.object.email %>
      <% end %>
    </div>
  <% end %>

  <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
    <li> <%= link_to "Blocipedia", welcome_index_path %> </li>
    <li> <%= link_to "About", welcome_about_path %> </li>
    <li> <%= link_to "Wikis", wikis_path %> </li>
    <li> <%= link_to "Users", users_path %> </li>



    <div class="pull-right user-info">
    <% if user_signed_in? %>
      Signed in as: <strong> <%= current_user.email %> </strong> |
      <%= link_to "Edit profile", edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %> |

      <% if current_user.role == 'standard' || current_user.role == 'admin' %>
        <%= link_to "Upgrade to Premium", new_charge_path %>
      <% else %>
        <%= link_to "Downgrade to Standard", edit_user_registration_path %>
      <% end %>

    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> -
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
    <% end %>
    </div>
  </ul>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
<% end %>

<%= yield %>
  </div>

<%= yield :analytic %>

</body>
</html>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1> Blocipedia Users </h1>

<div class="row">
  <div class="col-md-8">
    <% @users.each do |user| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            Email: <%= user.email %> <br>Role:  <%= user.role.capitalize %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% content_for :analytic do %>
  <script type="text/javascript"> $(document).ready(function(){ blocmetrics.report("User Index Visit"); }); </script>
<% end %>

app/views/users/new.html.erb
<h2> Sign Up </h2>

<div class="row">
  <div class="col-md-8">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <h4> <%= pluralize(@user.errors.count, "error") %>. </h4>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li> <%= msg %> </li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_group_tag(@user.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
      <% end %>

      <%= form_group_tag(@user.errors[:email]) do %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
      <% end %>

      <%= form_group_tag(@user.errors[:password]) do %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
      <% end %>

      <%= form_group_tag(@user.errors[:password_confirmation]) do %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
      <% end %>

      <div class="form-group">
        <%= f.submit "Sign Up", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>Blocipedia</h1>
<p>SaaS Collaboration Wiki made as an Independent Project - Brandon Wieber</p>

<% content_for :analytic do %>
  <script type="text/javascript"> $(document).ready(function(){ blocmetrics.report("About Page Visit"); }); </script>
<% end %>

app/views/welcome/index.html.erb
<br>

<div class="heading">
  <h1> Blocipedia: Social, Markdown Enabled Wikis </h1>

  <div class="box">
    <h3> Create and Share Markdown Wikis </h3>
    <p>
      <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %>
    </p>
  </div>
</div>


<div class="row">
  <div class="col-md-6">
    <h4 class="free-location"> Create Public Wikis </h4>
    <div class="free-button">
      <%= link_to "Free Plan", new_user_path, class: 'btn btn-info' %>
    </div>
  </div>

  <div class="col-md-5">
    <h4 class='premium-location'> Create Private Wikis </h4>
    <div class='premium-button'>
    <%= link_to "Premium Plan", new_charge_path, class: 'btn btn-info' %>
    </div>
  </div>
</div>

<% content_for :analytic do %>
  <script type="text/javascript"> $(document).ready(function(){ blocmetrics.report("Home Page Visit"); }); </script>
<% end %>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>

  <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>

  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>

  <% if @wiki.private %>
     <%= render partial: 'collaborators/form', locals: { f: f } %>
  <% end %>

  <%= f.submit "Save", class: 'btn btn-success' %>

<% end %>

app/views/wikis/edit.html.erb
<h1> Edit Wiki </h1>

<div class="row">
    <div class="col-md-4">
      <p> Guidelines for Wikis : </p>
      <ul>
        <li> Ensure your wiki is not a duplicate. </li>
        <li> Proofread! </li>
        <li> Fact check before posting. </li>
      </ul>
    </div>
    <div class="col-md-8">

      <%= render partial: 'wikis/form' %>

    </div>
</div>

app/views/wikis/index.html.erb
<h1> <div class="col-md-4">
  <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
</div> </h1>

  <div class="row">
    <h1 class="wiki-center"> Public Wikis </h1>
      <div class="box-solid">
        <% @wikis.each do |wiki| %>
          <div class="media">
            <div class="media-body">
              <h4 class="media-heading">
                <%= link_to markdown(wiki.title), wiki %> <% if wiki.private? %> PRIVATE <% end %>
              </h4>
              <small>
                <%= markdown(wiki.body) %> ________________________________________________________________________________________
              </small>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <% content_for :analytic do %>
      <script type="text/javascript"> $(document).ready(function(){ blocmetrics.report("Wiki Index Visit"); }); </script>
    <% end %>

app/views/wikis/new.html.erb
<h1> New Wiki </h1>

<div class="row">
    <div class="col-md-4">
      <p> Guidelines for Wikis : </p>
      <ul>
        <li> Ensure your wiki is not a duplicate. </li>
        <li> Proofread! </li>
        <li> Fact check before posting. </li>
      </ul>
    </div>
    <div class="col-md-8">
      <%= render partial: 'wikis/form' %>
    </div>
</div>

app/views/wikis/show.html.erb
<div class="wiki-show">
  <h1> <%= markdown(@wiki.title) %> </h1>
    <small>
      submitted <%= time_ago_in_words(@wiki.created_at) %>
    </small>
    <div class="col-md-16">
      <p><%= markdown(@wiki.body) %></p>
      <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-primary' %>

      <div class="user-info pull-right">
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
      </div>
    </div>

    <% if @wiki.private %>
      <% if Collaborator.exists?(wiki_id: @wiki) %>
        <%= render partial: 'collaborators/users' %>
      <% end %>
    <% end %>


    <% content_for :analytic do %>
      <script type="text/javascript"> $(document).ready(function(){ blocmetrics.report("Wiki Show"); }); </script>
    <% end %>